# Generated by Django 3.1.3 on 2020-11-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id_comprador', models.AutoField(help_text='ID Comprador', primary_key=True, serialize=False)),
                ('nombre_comprador', models.TextField(help_text='Nombre Comprador', max_length=30)),
                ('apellido_comprador', models.TextField(help_text='Apellido Comprador', max_length=30)),
                ('fono_comprador', models.CharField(help_text='Fono Comprador', max_length=12)),
                ('dir_comprador', models.CharField(help_text='Dirección Comprador', max_length=30)),
                ('comuna_comprador', models.CharField(choices=[('CE', 'Cerrillos'), ('CN', 'Cerro Navia'), ('CO', 'Conchalí'), ('EB', 'El Bosque'), ('EC', 'Estación Central'), ('HU', 'Huechuraba'), ('IN', 'Independencia'), ('LA', 'La Cisterna'), ('LF', 'La Florida'), ('LG', 'La Granja'), ('LP', 'La Pintana'), ('LR', 'La Reina'), ('LC', 'Las Condes'), ('LB', 'Lo Barnechea'), ('LE', 'Lo Espejo'), ('LP', 'Lo Prado'), ('MA', 'Macul'), ('MP', 'Maipú'), ('ÑU', 'Ñuñoa'), ('PH', 'Padre Hurtado'), ('PAC', 'Pedro Aguirre Cerda'), ('PE', 'Peñalolén'), ('PI', 'Pirque'), ('PR', 'Providencia'), ('PU', 'Pudahuel'), ('PA', 'Puente Alto'), ('QU', 'Quilicura'), ('QN', 'Quinta Normal'), ('REC', 'Recoleta'), ('REN', 'Renca'), ('SB', 'San Bernardo'), ('SJ', 'San Joaquín'), ('SJM', 'San José de Maipo'), ('SM', 'San Miguel'), ('SR', 'San Ramón'), ('SAN', 'Santiago')], help_text='Comuna Comprador', max_length=3)),
                ('email_comprador', models.EmailField(help_text='E-mail Comprador', max_length=25)),
                ('pass_comprador', models.CharField(help_text='Password Comprador', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(help_text='ID Vendedor', primary_key=True, serialize=False)),
                ('nombre_vendedor', models.TextField(help_text='Nombre Vendedor', max_length=30)),
                ('apellido_vendedor', models.TextField(help_text='Apellido Vendedor', max_length=30)),
                ('fono_vendedor', models.CharField(help_text='Fono Vendedor', max_length=12)),
                ('dir_vendedor', models.CharField(help_text='Dirección Vendedor', max_length=30)),
                ('com_vendedor', models.TextField(choices=[('CE', 'Cerrillos'), ('CN', 'Cerro Navia'), ('CO', 'Conchalí'), ('EB', 'El Bosque'), ('EC', 'Estación Central'), ('HU', 'Huechuraba'), ('IN', 'Independencia'), ('LA', 'La Cisterna'), ('LF', 'La Florida'), ('LG', 'La Granja'), ('LP', 'La Pintana'), ('LR', 'La Reina'), ('LC', 'Las Condes'), ('LB', 'Lo Barnechea'), ('LE', 'Lo Espejo'), ('LP', 'Lo Prado'), ('MA', 'Macul'), ('MP', 'Maipú'), ('ÑU', 'Ñuñoa'), ('PH', 'Padre Hurtado'), ('PAC', 'Pedro Aguirre Cerda'), ('PE', 'Peñalolén'), ('PI', 'Pirque'), ('PR', 'Providencia'), ('PU', 'Pudahuel'), ('PA', 'Puente Alto'), ('QU', 'Quilicura'), ('QN', 'Quinta Normal'), ('REC', 'Recoleta'), ('REN', 'Renca'), ('SB', 'San Bernardo'), ('SJ', 'San Joaquín'), ('SJM', 'San José de Maipo'), ('SM', 'San Miguel'), ('SR', 'San Ramón'), ('SAN', 'Santiago')], help_text='Comuna Vendedor', max_length=3)),
                ('email_vendedor', models.EmailField(help_text='E-mail Vendedor', max_length=25)),
                ('pass_vendedor', models.CharField(help_text='Password Vendedor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(help_text='ID Tarjeta', primary_key=True, serialize=False)),
                ('nro_tarjeta', models.IntegerField(help_text='Nro Tarjeta')),
                ('nombre_titular', models.TextField(help_text='Nombre del titular de la tarjeta', max_length=25)),
                ('banco', models.TextField(choices=[('S', 'Banco Bci'), ('M', 'Banco de Chile'), ('S', 'Banco Estado'), ('M', 'Banco Santander'), ('S', 'Banco BICE'), ('M', 'Banco Condell'), ('S', 'Banco CrediChile'), ('M', 'Banco Edwards Citi'), ('S', 'Banco Falabella'), ('M', 'Banco Internacional'), ('S', 'Banco Itaú'), ('M', 'Banco Ripley'), ('S', 'Banco Security'), ('M', 'Scotiabank')], help_text='Nombre del banco', max_length=1)),
                ('mes_vencimiento', models.CharField(help_text='Mes de vencimiento', max_length=2)),
                ('anno_vencimiento', models.CharField(help_text='Año de vencimiento', max_length=4)),
                ('comprador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categorias.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(help_text='ID Producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.TextField(help_text='Nombre del producto', max_length=25)),
                ('precio_producto', models.IntegerField(help_text='Precio')),
                ('descripcion_producto', models.TextField(help_text='Nombre del producto', max_length=25)),
                ('unidad_medida', models.CharField(choices=[('S', 'Kilogramo'), ('M', 'Gramo'), ('S', 'Unidad'), ('M', 'Docena'), ('S', 'Trozo')], help_text='Unidad de medida', max_length=1)),
                ('categoria', models.CharField(choices=[('PA', 'Pasteles'), ('T', 'Torta'), ('G', 'Galletas'), ('B', 'Bollería'), ('CH', 'Chocolates'), ('B', 'Bombones'), ('PI', 'Pizza'), ('S', 'Sandwiches'), ('F', 'Frituras'), ('CO', 'Comida Oriental')], help_text='Categoría', max_length=2)),
                ('imagen', models.ImageField(help_text='Foto producto', upload_to='')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_compra', models.AutoField(help_text='ID Compra', primary_key=True, serialize=False)),
                ('cant_prod', models.IntegerField(help_text='Cantidad de productos')),
                ('monto_total', models.IntegerField(help_text='Monto a pagar')),
                ('hora_compra', models.DateTimeField(help_text='Fecha y hora compra', max_length=30)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.comprador')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id_cuenta', models.AutoField(help_text='ID cuenta', primary_key=True, serialize=False)),
                ('nro_cuenta', models.IntegerField(help_text='Nro cuenta')),
                ('nombre_titular', models.TextField(help_text='Nombre del titular de la cuenta', max_length=25)),
                ('banco', models.TextField(choices=[('S', 'Banco Bci'), ('M', 'Banco de Chile'), ('S', 'Banco Estado'), ('M', 'Banco Santander'), ('S', 'Banco BICE'), ('M', 'Banco Condell'), ('S', 'Banco CrediChile'), ('M', 'Banco Edwards Citi'), ('S', 'Banco Falabella'), ('M', 'Banco Internacional'), ('S', 'Banco Itaú'), ('M', 'Banco Ripley'), ('S', 'Banco Security'), ('M', 'Scotiabank')], help_text='Nombre del banco', max_length=1)),
                ('tipo_cuenta', models.CharField(choices=[('CC', 'Cuenta Corriente'), ('CV', 'Cuenta Vista'), ('CR', 'Cuenta Rut')], help_text='Tipo de cuenta', max_length=20)),
                ('email_titular', models.EmailField(help_text='E-mail titular', max_length=25)),
                ('rut_titular', models.CharField(help_text='Rut titular', max_length=10)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categorias.vendedor')),
            ],
        ),
    ]
