# Generated by Django 3.1.3 on 2020-11-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20201116_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='apellido_comprador',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='comuna_comprador',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='dir_comprador',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='email_comprador',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='fono_comprador',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='id_comprador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='nombre_comprador',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='pass_comprador',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='usuario_comprador',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='apellido_vendedor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='com_vendedor',
            field=models.TextField(choices=[('CE', 'Cerrillos'), ('CN', 'Cerro Navia'), ('CO', 'Conchalí'), ('EB', 'El Bosque'), ('EC', 'Estación Central'), ('HU', 'Huechuraba'), ('IN', 'Independencia'), ('LA', 'La Cisterna'), ('LF', 'La Florida'), ('LG', 'La Granja'), ('LP', 'La Pintana'), ('LR', 'La Reina'), ('LC', 'Las Condes'), ('LB', 'Lo Barnechea'), ('LE', 'Lo Espejo'), ('LP', 'Lo Prado'), ('MA', 'Macul'), ('MP', 'Maipú'), ('ÑU', 'Ñuñoa'), ('PH', 'Padre Hurtado'), ('PAC', 'Pedro Aguirre Cerda'), ('PE', 'Peñalolén'), ('PI', 'Pirque'), ('PR', 'Providencia'), ('PU', 'Pudahuel'), ('PA', 'Puente Alto'), ('QU', 'Quilicura'), ('QN', 'Quinta Normal'), ('REC', 'Recoleta'), ('REN', 'Renca'), ('SB', 'San Bernardo'), ('SJ', 'San Joaquín'), ('SJM', 'San José de Maipo'), ('SM', 'San Miguel'), ('SR', 'San Ramón'), ('SAN', 'Santiago')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dir_vendedor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email_vendedor',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='fono_vendedor',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='id_vendedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre_vendedor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='pass_vendedor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario_vendedor',
            field=models.CharField(max_length=15),
        ),
    ]
