# Generated by Django 3.1.3 on 2020-11-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20201116_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(help_text='Nombre del producto', max_length=25),
        ),
    ]
